export enum ChainIdEnum {
  POLYGON = "80002",
  BINANCE_SMART_CHAIN = "97",
  ETHEREUM = "11155111",
  TRON = "TRON",
  BITCOIN = "BTC",
}

export enum NetworkEnum {
  POLYGON = "POLYGON",
  BINANCE_SMART_CHAIN = "BINANCE SMART CHAIN",
  ETHEREUM = "ETHEREUM",
  TRON = "TRON",
  BITCOIN = "BITCOIN",
}
